### ISSUE TITLE
Fully implement the sessions example

### ISSUE THREAD

**Issue by Michael-F-Bryan** [Michael-F-Bryan/libsignal-protocol-rs#23]
We need to write up a valid example showing how to establish a session and transfer messages. 

I've imemented most of the "sessions" example as written in the C library's README, but I'm not 100% sure it's implemented correctly. Unfortunately, the example elides a lot of useful stuff like key generation and trusting the other party's public key, so we've had to guess how that's meant to be done.

It'd be awesome if we could find a test for establishing sessions in the C library's tests!

**Comment by shekohex** [comment]
I think this now should be closed ? since the session example is now working :smile:

**Comment by Josef-Reichardt** [comment]
Sorry for answering on this old and closed issue but I'm still searching far a complete example. As far as I can see the [session example](https://github.com/Michael-F-Bryan/libsignal-protocol-rs/blob/master/libsignal-protocol/examples/sessions.rs) stops after encrypting the message but sending the message is missing. Am I right?

Does there exist more examples somewhere else? Actually I'm searching for an example of sending a message to a group. Or is this not possible yet with this library? I also want to receive messages in a group. Is this possible and is there an example too?

**Comment by rubdos** [comment]
`libsignal-protocol-rs` only implements the ratchet crypto. For messages and socket stuff, you need https://github.com/Michael-F-Bryan/libsignal-service-rs. Look at https://gitlab.com/rubdos/whisperfish/-/blob/master/src/worker/client.rs#L519 for something *working*, but not very clean (because we're coming from a legacy Go implementation). Look at https://github.com/gferon/signal-bot-rs/ for something more clean.

Afaik, GroupsV2 is not 100% ready yet, but we've got that as the next thing on the planning.
