### ISSUE TITLE
Error handling: get rid of opaque `failure::Error` in favour of custom errors

### ISSUE THREAD

**Issue by rubdos** [Michael-F-Bryan/libsignal-protocol-rs#59]
`StoreContext::load_session` returns `failure::Error`. This being a library, methods should return custom error types, as to enable dispatch on the errors.

**Comment by Michael-F-Bryan** [comment]
Something to keep in mind is you don't always have a well-defined set of errors to return. It's okay to return concrete errors from types we have control of, but for things like the `SessionStore` trait you need to provide an escape hatch that implementations can use when their particular error doesn't fit well into `InternalError`.

I wholeheartedly agree with using more specific error types where possible., though. Normally I'll write the `Display` and `std::error::Error` boilerplate by hand to avoid adding a proc-macro dependency, otherwise `thiserror` makes this pattern really easy to implement.

**Comment by rubdos** [comment]
Hmm, fair point. Maybe a `Custom` variant would be useful in that case? We should be able to dispatch on most common errors though.  Maybe we should add a few things that may come up for implementors (`IoError` comes to mind).
